const Genre = [
    "Abstract Strategy",
    "Action",
    "Adventure",
    "Ancient",
    "Animals",
    "Aviation/Flight",
    "Bluffing",
    "Book",
    "Card Game",
    "Children's Game",
    "City Building",
    "Civilization",
    "Collectable Components",
    "Comic Book",
    "Deduction",
    "Dice",
    "Economic",
    "Educational",
    "Environmental",
    "Expansion",
    "Exploration",
    "Fantasy",
    "Farming",
    "Fighting",
    "Historical",
    "Horror",
    "Humor",
    "Industry/Manufacturing",
    "Mafia",
    "Math",
    "Mature/Adult",
    "Maze",
    "Medical",
    "Medieval",
    "Memory",
    "Movies/TV/Radio theme",
    "Murder/Mystery",
    "Music",
    "Mythology",
    "Nautical",
    "Negotiation",
    "Party Game",
    "Pirates",
    "Political",
    "Puzzle",
    "Racing",
    "Real-time",
    "Religious",
    "Science Fiction",
    "Space Exploration",
    "Sports",
    "Trains",
    "Transportation",
    "Travel",
    "Trivia",
    "Video Game Theme",
    "War",
    "Word Game"
]

module.exports = Genre